name: Polls
description: ì˜ì‚¬ ê²°ì •ì„ ìœ„í•œ íˆ¬í‘œë¥¼ ì§„í–‰í•©ë‹ˆë‹¤.
labels: [poll]
body:
  - type: input
    id: topic
    attributes:
      label: ðŸ“Š íˆ¬í‘œ ì£¼ì œ
      placeholder: ì˜ˆ: ë¡œê·¸ì¸ ë°©ì‹ ê²°ì •

  - type: textarea
    id: background
    attributes:
      label: ðŸ“ ë°°ê²½ ì„¤ëª…
      placeholder: ì™œ íˆ¬í‘œê°€ í•„ìš”í•œì§€ ìž‘ì„±í•˜ì„¸ìš”.

  - type: textarea
    id: options
    attributes:
      label: âœ… ì˜µì…˜
      placeholder: Option A: ì„¤ëª…\nOption B: ì„¤ëª…\nOption C: ì„¤ëª…

  - type: input
    id: deadline
    attributes:
      label: ðŸ“… ë§ˆê°ì¼
      placeholder: YYYY-MM-DD

  - type: markdown
    attributes:
      value: |
        > **íˆ¬í‘œ ë°©ë²•**: ëŒ“ê¸€ë¡œ ì˜µì…˜ A/B/C ì¤‘ í•˜ë‚˜ë¥¼ ë‚¨ê²¨ì£¼ì„¸ìš”.
