spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goorm
    username: goorm-study
    password: goorm-study
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect




server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    org:
      chinoel:
        goormspring: DEBUG